spring.application.name=fx-risk-snapshot-api
# temporary disable docker compose during initial development phase, will enable it later when we have more services to integrate with
spring.docker.compose.enabled=false