spring.application.name=fx-risk-snapshot-api
# temporary setting for initial development (Docker, PostgreSQL)
spring.docker.compose.enabled=false

spring.application.name=fx-risk-snapshot-api

spring.docker.compose.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
